version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-github
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
