on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: corepack enable pnpm
      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency_id
        env:
          cache-name: cache-dependency
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('.node-version') }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-${{ env.cache-name }}
      - if: ${{ steps.cache_dependency_id.outputs.cache-hit != 'true' }}
        run: pnpm install --frozen-lockfile

      - run: pnpm run start
